services:
  ruokalistaserver:
    image: ${DOCKER_REGISTRY-}ruokalistaserver
    build:
      context: src
      dockerfile: Dockerfile
    ports:
        - "8080"
        - "8081"
    environment:
        - BackgroundsPath=
        - IG_ENABLED=true
        - Infotv_ENABLED=true
        - Aanestys_ENABLED=true
        - PrimaryColor=#f542cb
        - RootUser=root@kouluruokalista.fi
        - Branding=Testi ruokalista
        - Kasvisruokalista_ENABLED=true
        - DB_Server=10.10.0.203
        - DB_Database=Ruokalista-docker
        - DB_User=sa
        - DB_Password=TestiSalasana123!
        - DefaultRootPassword=TestiSalasana123!
        - API_ENABLED=true
        - JWT_Issuer=https://dev.kouluruokalista.fi
        - JWT_Audience=https://dev.kouluruokalista.fi
        - JWT_Secret=ChangeTheSecret

