# This is a basic workflow to help you get started with Actions

name: Dev autorun

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ Dev ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      - run: sudo systemctl stop ruokalistadev.service
      
      
      - run: dotnet publish /home/administrator/actions-runner-ruokalista/_work/RuokalistaServer/RuokalistaServer/RuokalistaServer.csproj -o /services/ruokalistadev
      
      - run: cp /services/ruokalistadev_temp/appsettings.json /services/ruokalistadev
      
      - run: sudo systemctl start ruokalista.service
      
      
      #- run: sleep 15
      #- run: sudo systemctl status ruokalistadev.service -n50
